"use client";
import { useEffect, useRef, useState } from "react";
import { Baby, CalendarDays, Check, Link2, Plus, ShieldCheck, Trash2, X } from "lucide-react";

type Child={id:string;name:string;birthday:string;phone:string;color:string};
const colors=[["紅","#df625e"],["橙","#e9974e"],["黃","#d8b33d"],["綠","#5b9b77"],["藍","#5888ca"],["靛","#626eb0"],["紫","#9367b6"]];
const demo:Child={id:"demo",name:"小禾",birthday:"2024-02-18",phone:"0912-345-678",color:"#5b9b77"};
const today=()=>new Date().toISOString().slice(0,10);
function age(date:string){const b=new Date(date),n=new Date();let y=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth(),d=n.getDate()-b.getDate();if(d<0){m--;d+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}return `${y}歲 ${m}個月 ${d}天`}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`field ${wide?"wide":""}`}><span>{label}</span>{children}</label>}
function Checks({title,items}:{title:string;items:string[]}){return <div className="checks"><strong>{title}</strong><div>{items.map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></div>}
function Choice({title,items,name,value,onChange}:{title:string;items:string[];name:string;value:string;onChange:(v:string)=>void}){return <div className="checks"><strong>{title}</strong><div>{items.map(x=><label key={x}><input type="radio" name={name} checked={value===x} onChange={()=>onChange(x)}/> {x}</label>)}</div></div>}
function TimeSelect({value,onChange}:{value:string;onChange:(v:string)=>void}){const [h="",m=""]=value.split(":");return <span className="time-select"><select aria-label="時" value={h} onChange={e=>onChange(`${e.target.value}:${m||"00"}`)}><option value="">--</option>{Array.from({length:24},(_,i)=>String(i).padStart(2,"0")).map(x=><option key={x}>{x}</option>)}</select><em>時</em><select aria-label="分" value={m} onChange={e=>onChange(`${h||"00"}:${e.target.value}`)}><option value="">--</option>{Array.from({length:60},(_,i)=>String(i).padStart(2,"0")).map(x=><option key={x}>{x}</option>)}</select><em>分</em></span>}
function SignaturePad({value,onSave}:{value:string;onSave:(v:string)=>void}){const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false);useEffect(()=>{if(value&&canvas.current){const img=new Image();img.onload=()=>canvas.current?.getContext("2d")?.drawImage(img,0,0,canvas.current!.width,canvas.current!.height);img.src=value}},[value]);const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*(e.currentTarget.width/r.width),y:(e.clientY-r.top)*(e.currentTarget.height/r.height)}};return <div className="signature-pad"><canvas ref={canvas} width="680" height="190" onPointerDown={e=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e),c=e.currentTarget.getContext("2d")!;c.beginPath();c.moveTo(p.x,p.y)}} onPointerMove={e=>{if(!drawing.current)return;const p=point(e),c=e.currentTarget.getContext("2d")!;c.lineWidth=3;c.lineCap="round";c.strokeStyle="#26352d";c.lineTo(p.x,p.y);c.stroke()}} onPointerUp={e=>{drawing.current=false;onSave(e.currentTarget.toDataURL())}}/><span>請家長在框內以手指或滑鼠簽名</span><button onClick={()=>{const c=canvas.current!;c.getContext("2d")?.clearRect(0,0,c.width,c.height);onSave("")}}>清除重簽</button></div>}
function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="card section"><header><b>{n}</b><h2>{title}</h2></header><div className="body">{children}</div></section>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="shade" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><header><h2>{title}</h2><button onClick={onClose}><X size={19}/></button></header>{children}</div></div>}

export default function Home(){
 const [open,setOpen]=useState(false),[pw,setPw]=useState(""),[err,setErr]=useState("");
 const [kids,setKids]=useState<Child[]>([demo]),[kidId,setKidId]=useState("demo"),[view,setView]=useState<"log"|"history">("log");
 const [data,setData]=useState<Record<string,string|boolean>>({}),[saved,setSaved]=useState(true),[add,setAdd]=useState(false),[del,setDel]=useState(false);
 const [activeDate,setActiveDate]=useState(today()),[creating,setCreating]=useState(true);
 const [deleteKid,setDeleteKid]=useState(false),[deletePw,setDeletePw]=useState(""),[deleteErr,setDeleteErr]=useState("");
 const [form,setForm]=useState({name:"",birthday:"",phone:"",color:"#5b9b77"});const kid=kids.find(k=>k.id===kidId)||kids[0];
 useEffect(()=>{const stored=localStorage.getItem("babysister-kids");if(stored)setKids(JSON.parse(stored));else localStorage.setItem("babysister-kids",JSON.stringify([demo]))},[]);
 useEffect(()=>{if(kid){const found=localStorage.getItem(`babysister-${kid.id}-${activeDate}`);setData(JSON.parse(found||"{}"));setCreating(activeDate===today()||!!found)}},[kid?.id,activeDate]);
 const set=(key:string,val:string|boolean)=>{const next={...data,[key]:val};setData(next);setSaved(false);setTimeout(()=>{localStorage.setItem(`babysister-${kid.id}-${activeDate}`,JSON.stringify(next));setSaved(true)},300)};
 const input=(key:string,type="text",ph="")=>type==="time"?<TimeSelect value={(data[key] as string)||""} onChange={v=>set(key,v)}/>:<input type={type} placeholder={ph} value={(data[key] as string)||""} onChange={e=>set(key,e.target.value)}/>;
 const addKid=()=>{if(!form.name||!form.birthday||!form.phone)return;const k={...form,id:crypto.randomUUID()},next=[...kids,k];setKids(next);setKidId(k.id);localStorage.setItem("babysister-kids",JSON.stringify(next));setAdd(false)};
 const removeKid=()=>{if(deletePw!=="611205"){setDeleteErr("密碼不正確，請再試一次");return}if(kids.length<=1){setDeleteErr("至少需要保留一名幼兒");return}const next=kids.filter(k=>k.id!==kid.id);Object.keys(localStorage).filter(key=>key.startsWith(`babysister-${kid.id}-`)).forEach(key=>localStorage.removeItem(key));localStorage.setItem("babysister-kids",JSON.stringify(next));setKids(next);setKidId(next[0].id);setActiveDate(today());setDeleteKid(false);setDeletePw("");setDeleteErr("")};
 if(!open)return <main className="login"><div className="loginbox"><div className="logo"><Baby/></div><p className="eyebrow">BABYSISTER</p><h1>保母日誌</h1><p>每天的照護，都安心留存。</p><form onSubmit={e=>{e.preventDefault();pw==="611205"?setOpen(true):setErr("密碼不正確，請再試一次")}}><label>進入密碼<input autoFocus type="password" inputMode="numeric" placeholder="請輸入密碼" value={pw} onChange={e=>{setPw(e.target.value);setErr("")}}/></label>{err&&<p className="error">{err}</p>}<button>進入日誌</button></form><small><ShieldCheck size={14}/> 資料僅供授權人員查看</small></div></main>;
 return <main className="app" style={{"--accent":kid.color} as React.CSSProperties}>
  <aside><div className="brand"><div className="logo"><Baby size={20}/></div><div><strong>保母日誌</strong><small>BABYSISTER</small></div></div><div className="side-title"><span>幼兒名單</span><button onClick={()=>setAdd(true)}><Plus size={17}/></button></div>{kids.map(k=><button className={`kid ${k.id===kidId?"active":""}`} key={k.id} onClick={()=>{setKidId(k.id);setActiveDate(today());setView("log")}}><i style={{background:k.color}}>{k.name[0]}</i><span><b>{k.name}</b><small>{age(k.birthday)}</small></span></button>)}<button className="delete-kid" onClick={()=>setDeleteKid(true)}><Trash2 size={14}/>刪除目前幼兒</button><div className="autosave"><ShieldCheck size={16}/>輸入內容後<br/>會自動儲存</div></aside>
  <div className="content"><div className="mobile-kids">{kids.map(k=><button key={k.id} className={k.id===kidId?"active":""} onClick={()=>{setKidId(k.id);setActiveDate(today());setView("log")}}><i style={{background:k.color}}>{k.name[0]}</i>{k.name}</button>)}</div><header className="top"><div><button className="mobile-add" onClick={()=>setAdd(true)}><Plus size={16}/> 新增幼兒</button><p>{new Intl.DateTimeFormat("zh-TW",{dateStyle:"full"}).format(new Date(`${activeDate}T12:00:00`))}</p><h1>{kid.name}的照護日誌</h1><span>{age(kid.birthday)}</span></div><div className="actions"><small><Check size={14}/>{saved?"已自動儲存":"儲存中…"}</small><button onClick={()=>{if(view==="history"){setActiveDate(today());setView("log")}else setView("history")}}><CalendarDays size={17}/>{view==="log"?"查看紀錄":"回到今日"}</button></div></header>
  {view==="history"?<History childId={kid.id} onSelect={date=>{setActiveDate(date);setView("log")}}/>:<div className="journal">
   {data.dayStatus?<section className="card day-state"><span>{data.dayStatus==="absent"?"小孩沒來":"今天放假"}</span><p>此日期不需要填寫照護日誌。</p><button onClick={()=>{set("dayStatus","");setCreating(true)}}>我要修改</button></section>:!creating?<section className="card day-state empty"><span>當日沒有紀錄</span><p>這一天尚未填寫日誌，也沒有標記未到或放假。</p><button onClick={()=>setCreating(true)}>新增當日日誌</button></section>:<>
   <section className="card day-options"><div><b>今天不需要填日誌？</b><span>選擇後只會保留對應狀態</span></div><button onClick={()=>{setData({dayStatus:"absent"});localStorage.setItem(`babysister-${kid.id}-${activeDate}`,JSON.stringify({dayStatus:"absent"}))}}>小孩沒來</button><button onClick={()=>{setData({dayStatus:"holiday"});localStorage.setItem(`babysister-${kid.id}-${activeDate}`,JSON.stringify({dayStatus:"holiday"}))}}>今天放假</button></section>
   <section className="card quick"><Field label="送托時間">{input("arrival","time")}</Field><Field label="返家時間">{input("leave","time")}</Field><Field label="送托時數">{input("hours","number","0")}<em>小時</em></Field><Field label="早上體溫">{input("amTemp","number","36.5")}<em>°C</em></Field><Field label="下午體溫">{input("pmTemp","number","36.5")}<em>°C</em></Field><Field label="量測時間">{input("tempTime","time")}</Field></section>
   <Section n="01" title="飲食情形"><div className="grid"><Field label="喝奶時間">{input("milkTime","time")}</Field><Field label="奶量">{input("milk","number","0")}<em>cc</em></Field><Field label="用餐時間">{input("mealTime","time")}</Field><Field label="餐點內容／量">{input("mealAmount","text","例如：粥半碗、香蕉 1/2 根")}</Field></div><Choice title="用餐狀況" name="mealStatus" value={(data.mealStatus as string)||""} onChange={v=>set("mealStatus",v)} items={["正常","量多","量較少"]}/><Field wide label="原因補充"><textarea value={(data.mealNote as string)||""} onChange={e=>set("mealNote",e.target.value)}/></Field></Section>
   <Section n="02" title="睡眠情形"><div className="grid"><Field label="入睡時間">{input("sleepStart","time")}</Field><Field label="起床時間">{input("sleepEnd","time")}</Field></div><Choice title="睡眠狀況" name="sleepStatus" value={(data.sleepStatus as string)||""} onChange={v=>set("sleepStatus",v)} items={["安穩","普通","不安穩"]}/><Field wide label="原因補充"><textarea value={(data.sleepNote as string)||""} onChange={e=>set("sleepNote",e.target.value)}/></Field></Section>
   <Section n="03" title="排便與換尿布"><div className="grid"><Field label="排便時間">{input("poopTime","time")}</Field><Field label="換尿布時間">{input("diaperTime","time")}</Field></div><Choice title="排便顏色" name="poopColor" value={(data.poopColor as string)||""} onChange={v=>set("poopColor",v)} items={["正常","偏綠","偏黑","其他"]}/><Choice title="排便狀況" name="poopStatus" value={(data.poopStatus as string)||""} onChange={v=>set("poopStatus",v)} items={["正常","偏硬","偏稀","其他"]}/><div className="soft"><b>紅屁股</b><label><input type="radio" name="rash"/> 無</label><label><input type="radio" name="rash"/> 有</label><Field label="處理方式">{input("rashCare")}</Field></div></Section>
   <Section n="04" title="餵藥紀錄"><div className="meds">{[1,2,3,4].map(i=><div className="med" key={i}><Field label={`第 ${i} 次時間`}>{input(`medTime${i}`,"time")}</Field><Checks title="內容" items={["藥包","藥水","外用藥"]}/><Field label="份量／部位">{input(`medDetail${i}`)}</Field></div>)}</div></Section>
   <Section n="05" title="活動、情緒與用品"><Checks title="活動內容" items={["說故事","聽音樂／律動","戶外散步","玩玩具","生活常規建立","大肌肉活動","小肌肉活動","自我探索"]}/><Field wide label="其他活動說明"><textarea value={(data.activity as string)||""} onChange={e=>set("activity",e.target.value)}/></Field><Choice title="幼兒情緒" name="mood" value={(data.mood as string)||""} onChange={v=>set("mood",v)} items={["愉悅","穩定","哭鬧","生氣","反抗","緊張焦慮","其他"]}/><Checks title="用品補充" items={["尿布","濕紙巾","奶粉／母乳","衣褲","其他"]}/></Section>
   <Section n="06" title="健康狀況"><Checks title="整體狀況" items={["正常"]}/><Checks title="不適症狀" items={["發燒","嘔吐","腹瀉","流鼻涕","咳嗽"]}/><div className="grid"><Field label="發燒度數">{input("fever","number")}<em>°C</em></Field><Field label="嘔吐次數">{input("vomit","number")}<em>次</em></Field><Field label="腹瀉次數">{input("diarrhea","number")}<em>次</em></Field></div><Checks title="行為異常" items={["食慾差","昏睡","躁動","活力不佳","持續哭鬧"]}/><Checks title="外觀異常" items={["皮膚異狀（紅腫或瘀青）","外傷"]}/><Field wide label="其他健康狀況"><textarea value={(data.health as string)||""} onChange={e=>set("health",e.target.value)}/></Field></Section>
   <Section n="07" title="保親交流"><Field wide label="今日想告訴家長的事"><textarea className="large" placeholder="輸入照護觀察、提醒或想分享的事情…" value={(data.note as string)||""} onChange={e=>set("note",e.target.value)}/></Field></Section>
   <section className="card signatures"><div><b>家長電子簽名</b><SignaturePad value={(data.parentSignature as string)||""} onSave={v=>{set("parentSignature",v);set("signedAt",v?new Date().toLocaleString("zh-TW"):"")}}/><small>{data.signedAt?`已簽署：${data.signedAt}`:"簽名會連同日期、時間及當日日誌一併保存"}</small><button className="share-sign" disabled title="網站正式上線後即可產生家長專屬簽名連結"><Link2 size={15}/> 上線後可傳送家長簽名連結</button></div><div><b>托育人員署名</b>{input("carer","text","輸入保母姓名")}<small>完成當日日誌後署名</small></div></section>
   <button className="delete" onClick={()=>setDel(true)}><Trash2 size={16}/>刪除此日紀錄</button>
  </>}</div>}</div>
  {add&&<Modal title="新增幼兒" onClose={()=>setAdd(false)}><div className="modalform"><Field label="姓名"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="生日"><input type="date" value={form.birthday} onChange={e=>setForm({...form,birthday:e.target.value})}/></Field><Field label="緊急聯絡人電話"><input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><div className="palette"><span>識別顏色</span><div>{colors.map(([n,c])=><button aria-label={n} key={c} className={form.color===c?"chosen":""} style={{background:c}} onClick={()=>setForm({...form,color:c})}>{form.color===c&&<Check size={16}/>}</button>)}</div></div><button className="primary" onClick={addKid}>新增幼兒</button></div></Modal>}
  {del&&<Modal title="確定刪除此日紀錄？" onClose={()=>setDel(false)}><p className="warn">刪除後將無法復原，{kid.name}在這一天的所有日誌內容都會被移除。</p><div className="modalactions"><button onClick={()=>setDel(false)}>取消</button><button onClick={()=>{localStorage.removeItem(`babysister-${kid.id}-${activeDate}`);setData({});setCreating(activeDate===today());setDel(false)}}>是，刪除此紀錄</button></div></Modal>}
  {deleteKid&&<Modal title={`確認刪除${kid.name}紀錄？`} onClose={()=>{setDeleteKid(false);setDeletePw("");setDeleteErr("")}}><p className="warn">刪除後，這名幼兒以及所有留存日誌都無法復原。請輸入保母密碼確認。</p><label className="delete-password">輸入密碼<input autoFocus type="password" inputMode="numeric" value={deletePw} onChange={e=>{setDeletePw(e.target.value);setDeleteErr("")}} placeholder="請輸入密碼"/></label>{deleteErr&&<p className="error">{deleteErr}</p>}<div className="modalactions"><button onClick={()=>{setDeleteKid(false);setDeletePw("");setDeleteErr("")}}>取消</button><button onClick={removeKid}>刪除</button></div></Modal>}
 </main>
}

function History({childId,onSelect}:{childId:string;onSelect:(date:string)=>void}){const now=new Date(),months=[2,1,0].map(i=>new Date(now.getFullYear(),now.getMonth()-i,1));const [sel,setSel]=useState(months[2]);const total=new Date(sel.getFullYear(),sel.getMonth()+1,0).getDate(),pad=new Date(sel.getFullYear(),sel.getMonth(),1).getDay();return <div className="history"><div className="months">{months.map(m=><button key={m.toISOString()} className={m.getMonth()===sel.getMonth()?"active":""} onClick={()=>setSel(m)}><small>{m.getFullYear()}</small><b>{m.getMonth()+1}月</b></button>)}</div><section className="card calendar"><header><div><h2>{sel.getFullYear()} 年 {sel.getMonth()+1} 月</h2><p>每個日期都可點選查看或補登</p></div><span>● 週末／國定假日</span></header><div className="week">{"日一二三四五六".split("").map(x=><b key={x}>{x}</b>)}</div><div className="days">{Array.from({length:pad}).map((_,i)=><i key={i}/>)}{Array.from({length:total},(_,i)=>{const d=i+1,dow=new Date(sel.getFullYear(),sel.getMonth(),d).getDay(),date=`${sel.getFullYear()}-${String(sel.getMonth()+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,raw=typeof window!=="undefined"?localStorage.getItem(`babysister-${childId}-${date}`):null,record=raw?JSON.parse(raw):null,isToday=today()===date,label=record?.dayStatus==="absent"?"小孩沒來":record?.dayStatus==="holiday"?"今天放假":record?"已有紀錄":isToday?"今日":"尚無紀錄";return <button key={d} className={`${dow===0||dow===6?"red":""} ${isToday?"today":""} ${record?"recorded":""}`} onClick={()=>onSelect(date)}><b>{d}</b><small>{label}</small></button>})}</div></section></div>}
