"use client";
import { useEffect, useRef, useState } from "react";
import { Baby, CalendarDays, Check, Link2, Plus, ShieldCheck, Trash2, X } from "lucide-react";

type Child={id:string;name:string;birthday:string;phone:string;color:string};
type FamilyPayload={v:1;childId:string;childName:string;date:string;expiresAt:string;record:Record<string,string|boolean>;signature?:string;signedAt?:string;locked?:boolean};
const colors=[["紅","#df625e"],["橙","#e9974e"],["黃","#d8b33d"],["綠","#5b9b77"],["藍","#5888ca"],["靛","#626eb0"],["紫","#9367b6"]];
const demo:Child={id:"demo",name:"小禾",birthday:"2024-02-18",phone:"0912-345-678",color:"#5b9b77"};
const today=()=>new Date().toISOString().slice(0,10);
function age(date:string){const b=new Date(date),n=new Date();let y=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth(),d=n.getDate()-b.getDate();if(d<0){m--;d+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}return `${y}歲 ${m}個月 ${d}天`}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`field ${wide?"wide":""}`}><span>{label}</span>{children}</label>}
function Checks({title,items,value="",onChange}:{title:string;items:string[];value?:string;onChange?:(v:string)=>void}){const picked=value?value.split("｜"):[];return <div className="checks"><strong>{title}</strong><div>{items.map(x=><label key={x}><input type="checkbox" checked={picked.includes(x)} onChange={e=>{const next=e.target.checked?[...picked,x]:picked.filter(v=>v!==x);onChange?.(next.join("｜"))}}/> {x}</label>)}</div></div>}
function Choice({title,items,name,value,onChange}:{title:string;items:string[];name:string;value:string;onChange:(v:string)=>void}){return <div className="checks"><strong>{title}</strong><div>{items.map(x=><label key={x}><input type="radio" name={name} checked={value===x} onChange={()=>onChange(x)}/> {x}</label>)}</div></div>}
function TimeSelect({value,onChange}:{value:string;onChange:(v:string)=>void}){const [h="",m=""]=value.split(":");return <span className="time-select"><select aria-label="時" value={h} onChange={e=>onChange(`${e.target.value}:${m||"00"}`)}><option value="">--</option>{Array.from({length:24},(_,i)=>String(i).padStart(2,"0")).map(x=><option key={x}>{x}</option>)}</select><em>時</em><select aria-label="分" value={m} onChange={e=>onChange(`${h||"00"}:${e.target.value}`)}><option value="">--</option>{Array.from({length:60},(_,i)=>String(i).padStart(2,"0")).map(x=><option key={x}>{x}</option>)}</select><em>分</em></span>}
function SignaturePad({value,onSave}:{value:string;onSave:(v:string)=>void}){const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),path=useRef(value.startsWith("path:")?value.slice(5):"");useEffect(()=>{if(!canvas.current)return;const c=canvas.current.getContext("2d")!;c.clearRect(0,0,680,190);if(value.startsWith("path:")&&value.slice(5)){c.lineWidth=3;c.lineCap="round";c.strokeStyle="#26352d";c.stroke(new Path2D(value.slice(5)));path.current=value.slice(5)}else if(value){const img=new Image();img.onload=()=>c.drawImage(img,0,0,680,190);img.src=value}},[value]);const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.round((e.clientX-r.left)*(680/r.width)),y:Math.round((e.clientY-r.top)*(190/r.height))}};return <div className="signature-pad"><canvas ref={canvas} width="680" height="190" onPointerDown={e=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e),c=e.currentTarget.getContext("2d")!;path.current+=`M${p.x} ${p.y}`;c.beginPath();c.moveTo(p.x,p.y)}} onPointerMove={e=>{if(!drawing.current)return;const p=point(e),c=e.currentTarget.getContext("2d")!;path.current+=`L${p.x} ${p.y}`;c.lineWidth=3;c.lineCap="round";c.strokeStyle="#26352d";c.lineTo(p.x,p.y);c.stroke()}} onPointerUp={()=>{drawing.current=false;onSave(`path:${path.current}`)}}/><span>請家長在框內以手指或滑鼠簽名</span><button onClick={()=>{const c=canvas.current!;c.getContext("2d")?.clearRect(0,0,c.width,c.height);path.current="";onSave("")}}>清除重簽</button></div>}
function SignatureImage({value}:{value:string}){return value.startsWith("path:")?<svg className="signature-svg" viewBox="0 0 680 190" role="img" aria-label="家長電子簽名"><path d={value.slice(5)} fill="none" stroke="#26352d" strokeWidth="3" strokeLinecap="round"/></svg>:<img className="saved-signature" src={value} alt="家長電子簽名"/>}
function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="card section"><header><b>{n}</b><h2>{title}</h2></header><div className="body">{children}</div></section>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="shade" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><header><h2>{title}</h2><button onClick={onClose}><X size={19}/></button></header>{children}</div></div>}

const enc=(v:FamilyPayload)=>btoa(encodeURIComponent(JSON.stringify(v)).replace(/%([0-9A-F]{2})/g,(_,p)=>String.fromCharCode(parseInt(p,16)))).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"");
const dec=(v:string):FamilyPayload=>{const base=v.replaceAll("-","+").replaceAll("_","/").padEnd(Math.ceil(v.length/4)*4,"=");return JSON.parse(decodeURIComponent(Array.from(atob(base),c=>`%${c.charCodeAt(0).toString(16).padStart(2,"0")}`).join("")))};
const readable:Record<string,string>={arrival:"送托時間",leave:"返家時間",hours:"送托時數",amTemp:"早上體溫",pmTemp:"下午體溫",tempTime:"量測時間",milkTime:"喝奶時間",milk:"奶量",mealTime:"用餐時間",mealAmount:"餐點內容／量",mealStatus:"用餐狀況",mealNote:"用餐補充",sleepStart:"入睡時間",sleepEnd:"起床時間",sleepStatus:"睡眠狀況",sleepNote:"睡眠補充",poopTime:"排便時間",diaperTime:"換尿布時間",poopColor:"排便顏色",poopStatus:"排便狀況",rashCare:"紅屁股處理",medTime1:"第 1 次時間",medDetail1:"第 1 次份量／部位",medTime2:"第 2 次時間",medDetail2:"第 2 次份量／部位",medTime3:"第 3 次時間",medDetail3:"第 3 次份量／部位",medTime4:"第 4 次時間",medDetail4:"第 4 次份量／部位",activity:"其他活動",mood:"幼兒情緒",fever:"發燒度數",vomit:"嘔吐次數",diarrhea:"腹瀉次數",health:"其他健康狀況",note:"保親交流",carer:"托育人員"};

export default function Home(){
 const [family,setFamily]=useState<FamilyPayload|null|undefined>(undefined);
 useEffect(()=>{const read=()=>{const raw=location.hash.startsWith("#family=")?location.hash.slice(8):"";if(!raw){setFamily(null);return}try{setFamily(dec(raw))}catch{setFamily(null)}};read();addEventListener("hashchange",read);return()=>removeEventListener("hashchange",read)},[]);
 if(family===undefined)return null;
 if(family)return <FamilyView initial={family}/>;
 return <CaregiverApp/>;
}

function FamilyView({initial}:{initial:FamilyPayload}){
 const [payload,setPayload]=useState(initial),[signature,setSignature]=useState(initial.signature||""),[copied,setCopied]=useState(false),[imported,setImported]=useState(false);
 const expired=new Date()>new Date(payload.expiresAt);
 const confirm=()=>{if(!signature)return;const next={...payload,signature,signedAt:new Date().toLocaleString("zh-TW"),locked:true};setPayload(next);location.hash=`family=${enc(next)}`};
 const copySigned=async()=>{await navigator.clipboard.writeText(location.href);setCopied(true)};
 useEffect(()=>{if(!payload.locked||!payload.signature)return;try{const kids:Child[]=JSON.parse(localStorage.getItem("babysister-kids")||"[]");if(!kids.some(k=>k.id===payload.childId))return;const key=`babysister-${payload.childId}-${payload.date}`,current=JSON.parse(localStorage.getItem(key)||"{}");localStorage.setItem(key,JSON.stringify({...current,parentSignature:payload.signature,signedAt:payload.signedAt,signatureLocked:true,signatureExpiresAt:payload.expiresAt}));setImported(true)}catch{}},[payload]);
 if(expired)return <main className="family-page"><section className="family-shell expired"><ShieldCheck/><h1>此簽名連結已失效</h1><p>家屬簽名連結僅保留三個月，請聯絡托育人員。</p></section></main>;
 const sections=[
  ["送托與體溫",["arrival","leave","hours","amTemp","pmTemp","tempTime"]],
  ["飲食情形",["milkTime","milk","mealTime","mealAmount","mealStatus","mealNote"]],
  ["睡眠情形",["sleepStart","sleepEnd","sleepStatus","sleepNote"]],
  ["排便與換尿布",["poopTime","diaperTime","poopColor","poopStatus","rash","rashCare"]],
  ["餵藥紀錄",["medTime1","medItems1","medDetail1","medTime2","medItems2","medDetail2","medTime3","medItems3","medDetail3","medTime4","medItems4","medDetail4"]],
  ["活動、情緒與用品",["activities","activity","mood","supplies"]],
  ["健康狀況",["overall","symptoms","fever","vomit","diarrhea","behaviors","appearance","health"]],
  ["保親交流",["note","carer"]]
 ] as const;
 return <main className="family-page"><section className="family-shell"><p className="eyebrow">BABYSISTER · 家屬專用</p><h1>{payload.childName}的當日照護紀錄</h1><div className="family-meta"><span>{payload.date}</span><span>此頁只能查看與簽名</span></div>{payload.record.dayStatus?<div className="status-only">{payload.record.dayStatus==="absent"?"小孩沒來":"今天放假"}</div>:<div className="family-record">{sections.map(([title,keys])=><section key={title}><h2>{title}</h2><div className="readonly-record">{keys.map(k=><div key={k}><b>{readable[k]||({rash:"紅屁股",medItems1:"第 1 次用藥",medItems2:"第 2 次用藥",medItems3:"第 3 次用藥",medItems4:"第 4 次用藥",activities:"活動內容",supplies:"用品補充",overall:"整體狀況",symptoms:"不適症狀",behaviors:"行為異常",appearance:"外觀異常"} as Record<string,string>)[k]||k.replace(/([A-Z])/g," $1")}</b><span>{String(payload.record[k]||"—")}</span></div>)}</div></section>)}</div>}<section className="family-sign"><h2>家長簽名</h2>{payload.locked&&payload.signature?<><SignatureImage value={payload.signature}/><p><Check size={16}/> 已於 {payload.signedAt} 確認簽名，內容已鎖定不可更改。</p>{imported&&<p><Check size={16}/> 已自動收入此裝置的保母日誌。</p>}<button className="primary" onClick={copySigned}><Link2 size={16}/> {copied?"已複製完成連結":"複製完成連結"}</button><small>{copied?"請回到 LINE 對話，長按輸入框選擇貼上，再傳給保母。":"確認後請複製連結，再回到 LINE 貼上傳給保母。"}</small></>:<><SignaturePad value={signature} onSave={setSignature}/><button className="primary" disabled={!signature} onClick={confirm}>確認簽名</button><small>按下確認後即不可清除或重簽。</small></>}</section><footer>連結將於 {new Date(payload.expiresAt).toLocaleDateString("zh-TW")} 失效，且無法查看其他幼兒資料。</footer></section></main>
}

function CaregiverApp(){
 const [open,setOpen]=useState(false),[pw,setPw]=useState(""),[err,setErr]=useState("");
 const [kids,setKids]=useState<Child[]>([demo]),[kidId,setKidId]=useState("demo"),[view,setView]=useState<"log"|"history">("log");
 const [data,setData]=useState<Record<string,string|boolean>>({}),[saved,setSaved]=useState(true),[add,setAdd]=useState(false),[del,setDel]=useState(false),[deleteDayPw,setDeleteDayPw]=useState(""),[deleteDayErr,setDeleteDayErr]=useState("");
 const [activeDate,setActiveDate]=useState(today()),[creating,setCreating]=useState(true);
 const [deleteKid,setDeleteKid]=useState(false),[deletePw,setDeletePw]=useState(""),[deleteErr,setDeleteErr]=useState("");
 const [shareUrl,setShareUrl]=useState(""),[shareCopied,setShareCopied]=useState(false),[deleteSignature,setDeleteSignature]=useState(false),[signaturePw,setSignaturePw]=useState(""),[signatureErr,setSignatureErr]=useState("");
 const [form,setForm]=useState({name:"",birthday:"",phone:"",color:"#5b9b77"});const kid=kids.find(k=>k.id===kidId)||kids[0];
 useEffect(()=>{const stored=localStorage.getItem("babysister-kids");if(stored)setKids(JSON.parse(stored));else localStorage.setItem("babysister-kids",JSON.stringify([demo]))},[]);
 useEffect(()=>{if(kid){const found=localStorage.getItem(`babysister-${kid.id}-${activeDate}`);setData(JSON.parse(found||"{}"));setCreating(activeDate===today()||!!found)}},[kid?.id,activeDate]);
 const set=(key:string,val:string|boolean)=>{const next={...data,[key]:val};setData(next);setSaved(false);setTimeout(()=>{localStorage.setItem(`babysister-${kid.id}-${activeDate}`,JSON.stringify(next));setSaved(true)},300)};
 const input=(key:string,type="text",ph="")=>type==="time"?<TimeSelect value={(data[key] as string)||""} onChange={v=>set(key,v)}/>:<input type={type} placeholder={ph} value={(data[key] as string)||""} onChange={e=>set(key,e.target.value)}/>;
 const addKid=()=>{if(!form.name||!form.birthday||!form.phone)return;const k={...form,id:crypto.randomUUID()},next=[...kids,k];setKids(next);setKidId(k.id);localStorage.setItem("babysister-kids",JSON.stringify(next));setAdd(false)};
 const removeKid=()=>{if(deletePw!=="611205"){setDeleteErr("密碼不正確，請再試一次");return}if(kids.length<=1){setDeleteErr("至少需要保留一名幼兒");return}const next=kids.filter(k=>k.id!==kid.id);Object.keys(localStorage).filter(key=>key.startsWith(`babysister-${kid.id}-`)).forEach(key=>localStorage.removeItem(key));localStorage.setItem("babysister-kids",JSON.stringify(next));setKids(next);setKidId(next[0].id);setActiveDate(today());setDeleteKid(false);setDeletePw("");setDeleteErr("")};
 const makeFamilyLink=()=>{const exp=new Date(`${activeDate}T23:59:59`);exp.setMonth(exp.getMonth()+3);const clean=Object.fromEntries(Object.entries(data).filter(([k])=>!k.startsWith("parent")&&!k.startsWith("signature")&&k!=="signedAt"));const payload:FamilyPayload={v:1,childId:kid.id,childName:kid.name,date:activeDate,expiresAt:exp.toISOString(),record:clean};const url=`${location.origin}${location.pathname}#family=${enc(payload)}`;setShareUrl(url);setShareCopied(false)};
 if(!open)return <main className="login"><div className="loginbox"><div className="logo"><Baby/></div><p className="eyebrow">BABYSISTER</p><h1>保母日誌</h1><p>每天的照護，都安心留存。</p><form onSubmit={e=>{e.preventDefault();pw==="611205"?setOpen(true):setErr("密碼不正確，請再試一次")}}><label>進入密碼<input autoFocus type="password" inputMode="numeric" placeholder="請輸入密碼" value={pw} onChange={e=>{setPw(e.target.value);setErr("")}}/></label>{err&&<p className="error">{err}</p>}<button>進入日誌</button></form><small><ShieldCheck size={14}/> 資料僅供授權人員查看</small></div></main>;
 return <main className="app" style={{"--accent":kid.color} as React.CSSProperties}>
  <aside><div className="brand"><div className="logo"><Baby size={20}/></div><div><strong>保母日誌</strong><small>BABYSISTER</small></div></div><div className="side-title"><span>幼兒名單</span><button onClick={()=>setAdd(true)}><Plus size={17}/></button></div>{kids.map(k=><button className={`kid ${k.id===kidId?"active":""}`} key={k.id} onClick={()=>{setKidId(k.id);setActiveDate(today());setView("log")}}><i style={{background:k.color}}>{k.name[0]}</i><span><b>{k.name}</b><small>{age(k.birthday)}</small></span></button>)}<button className="delete-kid" onClick={()=>setDeleteKid(true)}><Trash2 size={14}/>刪除目前幼兒</button><div className="autosave"><ShieldCheck size={16}/>輸入內容後<br/>會自動儲存</div></aside>
  <div className="content"><div className="mobile-kids">{kids.map(k=><button key={k.id} className={k.id===kidId?"active":""} onClick={()=>{setKidId(k.id);setActiveDate(today());setView("log")}}><i style={{background:k.color}}>{k.name[0]}</i>{k.name}</button>)}</div><header className="top"><div><button className="mobile-add" onClick={()=>setAdd(true)}><Plus size={16}/> 新增幼兒</button><p>{new Intl.DateTimeFormat("zh-TW",{dateStyle:"full"}).format(new Date(`${activeDate}T12:00:00`))}</p><h1>{kid.name}的照護日誌</h1><span>{age(kid.birthday)}</span></div><div className="actions"><small><Check size={14}/>{saved?"已自動儲存":"儲存中…"}</small><button onClick={()=>{if(view==="history"){setActiveDate(today());setView("log")}else setView("history")}}><CalendarDays size={17}/>{view==="log"?"查看紀錄":"回到今日"}</button></div></header>
  {view==="history"?<History childId={kid.id} onSelect={date=>{setActiveDate(date);setView("log")}}/>:<div className="journal">
   {data.dayStatus?<section className="card day-state"><span>{data.dayStatus==="absent"?"小孩沒來":"今天放假"}</span><p>此日期不需要填寫照護日誌。</p><button onClick={()=>{set("dayStatus","");setCreating(true)}}>我要修改</button></section>:!creating?<section className="card day-state empty"><span>當日沒有紀錄</span><p>這一天尚未填寫日誌，也沒有標記未到或放假。</p><button onClick={()=>setCreating(true)}>新增當日日誌</button></section>:<>
   <section className="card day-options"><div><b>今天不需要填日誌？</b><span>選擇後只會保留對應狀態</span></div><button onClick={()=>{setData({dayStatus:"absent"});localStorage.setItem(`babysister-${kid.id}-${activeDate}`,JSON.stringify({dayStatus:"absent"}))}}>小孩沒來</button><button onClick={()=>{setData({dayStatus:"holiday"});localStorage.setItem(`babysister-${kid.id}-${activeDate}`,JSON.stringify({dayStatus:"holiday"}))}}>今天放假</button></section>
   <section className="card quick"><Field label="送托時間">{input("arrival","time")}</Field><Field label="返家時間">{input("leave","time")}</Field><Field label="送托時數">{input("hours","number","0")}<em>小時</em></Field><Field label="早上體溫">{input("amTemp","number","36.5")}<em>°C</em></Field><Field label="下午體溫">{input("pmTemp","number","36.5")}<em>°C</em></Field><Field label="量測時間">{input("tempTime","time")}</Field></section>
   <Section n="01" title="飲食情形"><div className="grid"><Field label="喝奶時間">{input("milkTime","time")}</Field><Field label="奶量">{input("milk","number","0")}<em>cc</em></Field><Field label="用餐時間">{input("mealTime","time")}</Field><Field label="餐點內容／量">{input("mealAmount","text","例如：粥半碗、香蕉 1/2 根")}</Field></div><Choice title="用餐狀況" name="mealStatus" value={(data.mealStatus as string)||""} onChange={v=>set("mealStatus",v)} items={["正常","量多","量較少"]}/><Field wide label="原因補充"><textarea value={(data.mealNote as string)||""} onChange={e=>set("mealNote",e.target.value)}/></Field></Section>
   <Section n="02" title="睡眠情形"><div className="grid"><Field label="入睡時間">{input("sleepStart","time")}</Field><Field label="起床時間">{input("sleepEnd","time")}</Field></div><Choice title="睡眠狀況" name="sleepStatus" value={(data.sleepStatus as string)||""} onChange={v=>set("sleepStatus",v)} items={["安穩","普通","不安穩"]}/><Field wide label="原因補充"><textarea value={(data.sleepNote as string)||""} onChange={e=>set("sleepNote",e.target.value)}/></Field></Section>
   <Section n="03" title="排便與換尿布"><div className="grid"><Field label="排便時間">{input("poopTime","time")}</Field><Field label="換尿布時間">{input("diaperTime","time")}</Field></div><Choice title="排便顏色" name="poopColor" value={(data.poopColor as string)||""} onChange={v=>set("poopColor",v)} items={["正常","偏綠","偏黑","其他"]}/><Choice title="排便狀況" name="poopStatus" value={(data.poopStatus as string)||""} onChange={v=>set("poopStatus",v)} items={["正常","偏硬","偏稀","其他"]}/><div className="soft"><b>紅屁股</b><label><input type="radio" name="rash" checked={data.rash==="無"} onChange={()=>set("rash","無")}/> 無</label><label><input type="radio" name="rash" checked={data.rash==="有"} onChange={()=>set("rash","有")}/> 有</label><Field label="處理方式">{input("rashCare")}</Field></div></Section>
   <Section n="04" title="餵藥紀錄"><div className="meds">{[1,2,3,4].map(i=><div className="med" key={i}><Field label={`第 ${i} 次時間`}>{input(`medTime${i}`,"time")}</Field><Checks title="內容" value={(data[`medItems${i}`] as string)||""} onChange={v=>set(`medItems${i}`,v)} items={["藥包","藥水","外用藥"]}/><Field label="份量／部位">{input(`medDetail${i}`)}</Field></div>)}</div></Section>
   <Section n="05" title="活動、情緒與用品"><Checks title="活動內容" value={(data.activities as string)||""} onChange={v=>set("activities",v)} items={["說故事","聽音樂／律動","戶外散步","玩玩具","生活常規建立","大肌肉活動","小肌肉活動","自我探索"]}/><Field wide label="其他活動說明"><textarea value={(data.activity as string)||""} onChange={e=>set("activity",e.target.value)}/></Field><Choice title="幼兒情緒" name="mood" value={(data.mood as string)||""} onChange={v=>set("mood",v)} items={["愉悅","穩定","哭鬧","生氣","反抗","緊張焦慮","其他"]}/><Checks title="用品補充" value={(data.supplies as string)||""} onChange={v=>set("supplies",v)} items={["尿布","濕紙巾","奶粉／母乳","衣褲","其他"]}/></Section>
   <Section n="06" title="健康狀況"><Checks title="整體狀況" value={(data.overall as string)||""} onChange={v=>set("overall",v)} items={["正常"]}/><Checks title="不適症狀" value={(data.symptoms as string)||""} onChange={v=>set("symptoms",v)} items={["發燒","嘔吐","腹瀉","流鼻涕","咳嗽"]}/><div className="grid"><Field label="發燒度數">{input("fever","number")}<em>°C</em></Field><Field label="嘔吐次數">{input("vomit","number")}<em>次</em></Field><Field label="腹瀉次數">{input("diarrhea","number")}<em>次</em></Field></div><Checks title="行為異常" value={(data.behaviors as string)||""} onChange={v=>set("behaviors",v)} items={["食慾差","昏睡","躁動","活力不佳","持續哭鬧"]}/><Checks title="外觀異常" value={(data.appearance as string)||""} onChange={v=>set("appearance",v)} items={["皮膚異狀（紅腫或瘀青）","外傷"]}/><Field wide label="其他健康狀況"><textarea value={(data.health as string)||""} onChange={e=>set("health",e.target.value)}/></Field></Section>
   <Section n="07" title="保親交流"><Field wide label="今日想告訴家長的事"><textarea className="large" placeholder="輸入照護觀察、提醒或想分享的事情…" value={(data.note as string)||""} onChange={e=>set("note",e.target.value)}/></Field></Section>
   <section className="card signatures"><div><b>家長簽名</b>{data.parentSignature?<><SignatureImage value={data.parentSignature as string}/><small>已確認簽名：{String(data.signedAt||"")}</small><button className="remove-sign" onClick={()=>setDeleteSignature(true)}><Trash2 size={14}/> 刪除家長簽名</button></>:<><p className="signature-note">保母頁面不提供代簽。請產生只限本日內容的家屬連結，由家長本人查看並簽名。</p><button className="share-sign" onClick={makeFamilyLink}><Link2 size={15}/> 產生家屬檢視／簽名連結</button></>}</div><div><b>托育人員署名</b>{input("carer","text","輸入保母姓名")}<small>完成當日日誌後署名</small></div></section>
   <button className="delete" onClick={()=>setDel(true)}><Trash2 size={16}/>刪除此日紀錄</button>
  </>}</div>}</div>
  {add&&<Modal title="新增幼兒" onClose={()=>setAdd(false)}><div className="modalform"><Field label="姓名"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="生日"><input type="date" value={form.birthday} onChange={e=>setForm({...form,birthday:e.target.value})}/></Field><Field label="緊急聯絡人電話"><input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><div className="palette"><span>識別顏色</span><div>{colors.map(([n,c])=><button aria-label={n} key={c} className={form.color===c?"chosen":""} style={{background:c}} onClick={()=>setForm({...form,color:c})}>{form.color===c&&<Check size={16}/>}</button>)}</div></div><button className="primary" onClick={addKid}>新增幼兒</button></div></Modal>}
  {shareUrl&&<Modal title="家屬檢視／簽名連結" onClose={()=>setShareUrl("")}><p className="warn">此連結只能查看{kid.name}在 {activeDate} 的內容與簽名，不能修改日誌，也不能查看其他幼兒紀錄。家長確認簽名後，請將完成連結回傳給保母匯入。</p><textarea className="share-url" readOnly value={shareUrl}/><div className="modalactions"><button onClick={()=>setShareUrl("")}>關閉</button><button onClick={async()=>{await navigator.clipboard.writeText(shareUrl);setShareCopied(true)}}>{shareCopied?"已複製":"複製連結"}</button></div></Modal>}
  {del&&<Modal title="確定刪除此日紀錄？" onClose={()=>{setDel(false);setDeleteDayPw("");setDeleteDayErr("")}}><p className="warn">刪除後將無法復原，{kid.name}在這一天的所有日誌內容都會被移除。請輸入保母密碼確認。</p><label className="delete-password">輸入密碼<input autoFocus type="password" inputMode="numeric" value={deleteDayPw} onChange={e=>{setDeleteDayPw(e.target.value);setDeleteDayErr("")}} placeholder="請輸入密碼"/></label>{deleteDayErr&&<p className="error">{deleteDayErr}</p>}<div className="modalactions"><button onClick={()=>setDel(false)}>取消</button><button onClick={()=>{if(deleteDayPw!=="611205"){setDeleteDayErr("密碼不正確，請再試一次");return}localStorage.removeItem(`babysister-${kid.id}-${activeDate}`);setData({});setCreating(activeDate===today());setDel(false);setDeleteDayPw("")}}>是，刪除此紀錄</button></div></Modal>}
  {deleteSignature&&<Modal title="刪除家長簽名？" onClose={()=>{setDeleteSignature(false);setSignaturePw("");setSignatureErr("")}}><p className="warn">只會刪除家長簽名，當日日誌內容會保留。請輸入保母密碼確認。</p><label className="delete-password">輸入密碼<input autoFocus type="password" inputMode="numeric" value={signaturePw} onChange={e=>{setSignaturePw(e.target.value);setSignatureErr("")}} placeholder="請輸入密碼"/></label>{signatureErr&&<p className="error">{signatureErr}</p>}<div className="modalactions"><button onClick={()=>setDeleteSignature(false)}>取消</button><button onClick={()=>{if(signaturePw!=="611205"){setSignatureErr("密碼不正確，請再試一次");return}const next={...data};delete next.parentSignature;delete next.signedAt;delete next.signatureLocked;delete next.signatureExpiresAt;setData(next);localStorage.setItem(`babysister-${kid.id}-${activeDate}`,JSON.stringify(next));setDeleteSignature(false);setSignaturePw("")}}>確認刪除簽名</button></div></Modal>}
  {deleteKid&&<Modal title={`確認刪除${kid.name}紀錄？`} onClose={()=>{setDeleteKid(false);setDeletePw("");setDeleteErr("")}}><p className="warn">刪除後，這名幼兒以及所有留存日誌都無法復原。請輸入保母密碼確認。</p><label className="delete-password">輸入密碼<input autoFocus type="password" inputMode="numeric" value={deletePw} onChange={e=>{setDeletePw(e.target.value);setDeleteErr("")}} placeholder="請輸入密碼"/></label>{deleteErr&&<p className="error">{deleteErr}</p>}<div className="modalactions"><button onClick={()=>{setDeleteKid(false);setDeletePw("");setDeleteErr("")}}>取消</button><button onClick={removeKid}>刪除</button></div></Modal>}
 </main>
}

function History({childId,onSelect}:{childId:string;onSelect:(date:string)=>void}){const now=new Date(),months=[2,1,0].map(i=>new Date(now.getFullYear(),now.getMonth()-i,1));const [sel,setSel]=useState(months[2]);const total=new Date(sel.getFullYear(),sel.getMonth()+1,0).getDate(),pad=new Date(sel.getFullYear(),sel.getMonth(),1).getDay();return <div className="history"><div className="months">{months.map(m=><button key={m.toISOString()} className={m.getMonth()===sel.getMonth()?"active":""} onClick={()=>setSel(m)}><small>{m.getFullYear()}</small><b>{m.getMonth()+1}月</b></button>)}</div><section className="card calendar"><header><div><h2>{sel.getFullYear()} 年 {sel.getMonth()+1} 月</h2><p>每個日期都可點選查看或補登</p></div><span>● 週末／國定假日</span></header><div className="week">{"日一二三四五六".split("").map(x=><b key={x}>{x}</b>)}</div><div className="days">{Array.from({length:pad}).map((_,i)=><i key={i}/>)}{Array.from({length:total},(_,i)=>{const d=i+1,dow=new Date(sel.getFullYear(),sel.getMonth(),d).getDay(),date=`${sel.getFullYear()}-${String(sel.getMonth()+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,raw=typeof window!=="undefined"?localStorage.getItem(`babysister-${childId}-${date}`):null,record=raw?JSON.parse(raw):null,isToday=today()===date,label=record?.dayStatus==="absent"?"小孩沒來":record?.dayStatus==="holiday"?"今天放假":record?"已有紀錄":isToday?"今日":"尚無紀錄";return <button key={d} className={`${dow===0||dow===6?"red":""} ${isToday?"today":""} ${record?"recorded":""}`} onClick={()=>onSelect(date)}><b>{d}</b><small>{label}</small></button>})}</div></section></div>}
